name: Sync Repository

on:
  push:
    branches:
      - main  # 根据需要修改分支名称
    schedule:
      - cron: "5 16 * * *"  # 每天北京时间 0 点运行
    workflow_dispatch:      # 也可以手动触发

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Sync to Destination Repository
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://cnb.cool/ttf248/ttf248.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.CNB_PAT }}
