name: Sync to Other Platforms

on:
  push:
    branches:
      - main  # 你可以改成其他分支
    schedule:
      - cron: "0 16 * * *"  # 每天北京时间 0 点运行
    workflow_dispatch:     # 也可以手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 关键！防止 shallow push 报错

      - name: Set Git config
        run: |
          git config --global user.name "tianlong.xiang"
          git config --global user.email "tianlong.xiang@foxmail.com"

      - name: Mirror to CNB
        env:
          CNB_TOKEN: ${{ secrets.CNB_PAT }}
        run: |
          git remote add cnb https://oauth2:${CNB_TOKEN}@cnb.cool/ttf248/ttf248.git
          git push --mirror cnb
